"""add salary change request

Revision ID: 1130809df7fb
Revises: 2c8f1b9a4d2e
Create Date: 2026-03-26 21:14:17.023290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1130809df7fb'
down_revision = '2c8f1b9a4d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_role', sa.String(length=20), nullable=True),
    sa.Column('proposed_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proposed_bonus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    op.drop_table('worker_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('worker_tasks_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feedback',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('feedback_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('salary_change_requests')
    # ### end Alembic commands ###
