"""add worker attendance totals

Revision ID: 35af4a432bc1
Revises: 
Create Date: 2026-03-03 23:39:26.313556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35af4a432bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_present', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('days_absent', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('days_absent')
        batch_op.drop_column('days_present')

    # ### end Alembic commands ###
